"""Collect every results/**/summary.json into results/RESULTS.md.

    python3 tools/report.py

One table per orchestrator (Step Functions, durable, CLI), one row per scenario, each row
linking to the directory that holds the input, history, output, logs, and summary it was built
from. Rows are read, never written: a scenario with no summary.json is listed as "not run".
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(ROOT, "results")
ORDER = ["single", "parallel", "retryable-fail", "hang", "fanout-4", "fanout-8", "fanout-refused",
         "fanout-approved", "fanout-denied"]
TITLES = {"stepfunctions": "Step Functions", "durable": "Lambda durable function"}


def load(orch: str) -> dict[str, dict]:
    base = os.path.join(RESULTS, orch)
    out = {}
    if not os.path.isdir(base):
        return out
    for name in sorted(os.listdir(base)):
        path = os.path.join(base, name, "summary.json")
        if os.path.exists(path):
            with open(path) as f:
                out[name] = json.load(f)
    return out


def fmt_secs(v) -> str:
    return f"{float(v):.1f} s" if isinstance(v, (int, float)) else "-"


def table(orch: str, rows: dict[str, dict]) -> str:
    lines = [f"## {TITLES.get(orch, orch)}", "",
             "| scenario | status | by the service's clock | VMs | RunMicrovm calls | as expected | what the history shows |",
             "|---|---|---|---|---|---|---|"]
    names = [n for n in ORDER if n in rows] + [n for n in rows if n not in ORDER]
    for n in ORDER:
        if n not in rows:
            lines.append(f"| `{n}` | not run | - | - | - | - | - |")
    for n in names:
        s = rows[n]
        ok = "yes" if s.get("matches_expected") else "**no**"
        notes = "; ".join(str(x) for x in (s.get("notes") or [])[:2]).replace("|", "\\|") or "-"
        link = f"[`{n}`]({orch}/{n}/)"
        lines.append(f"| {link} | {s.get('status', '-')} | {fmt_secs(s.get('seconds_by_service'))} | "
                     f"{len(s.get('vm_ids') or [])} | {s.get('runmicrovm_calls', '-')} | {ok} | {notes} |")
    return "\n".join(lines)


def cli_section() -> str:
    path = os.path.join(RESULTS, "cli", "summary.json")
    if not os.path.exists(path):
        return "## CLI\n\nnot run"
    with open(path) as f:
        s = json.load(f)
    present = sorted(x for x in os.listdir(os.path.join(RESULTS, "cli")) if not x.startswith("."))
    files = ", ".join(f"[{x}](cli/{x})" for x in present)
    return ("## CLI, no orchestrator\n\n"
            f"`mvm lease run demo-agent --kind none --wait` launched `{s.get('vm_id')}`; `mvm watch` followed it for "
            f"{s.get('watch_seconds')} s; the whole scenario took {s.get('wall_seconds')} s of wall time.\n\n"
            f"Files: {files}")


def bench_section() -> str:
    path = os.path.join(ROOT, "benchmarks", "results", "bench.md")
    if not os.path.exists(path):
        return "## Benchmarks\n\nnot run"
    with open(path) as f:
        return "## Benchmarks\n\n" + f.read().strip() + "\n\n![p50 end to end](../benchmarks/results/bench.png)"


def main() -> int:
    parts = ["# Results", "",
             "Every row links to the directory holding the exact input, the full execution history, the output, "
             "the VM's own log lines, the orchestrator's log lines, and the summary the row was generated from. "
             "Generated by `tools/report.py`; nothing here is typed in.", ""]
    for orch in ("stepfunctions", "durable"):
        parts.append(table(orch, load(orch)))
        parts.append("")
    parts += [cli_section(), "", bench_section(), ""]
    out = os.path.join(RESULTS, "RESULTS.md")
    with open(out, "w") as f:
        f.write("\n".join(parts))
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
